spring:
  application:
    name: reto
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: PRODUCTAPP
    password: root123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
